### ISSUE TITLE
infinite loading and other issue

### ISSUE THREAD

**Issue by Grumm1291** [agnirudrasil/avault#1]
so ive used this for a while and ive seen 2 issues, one has just recently arisen where out of nowhere, whenever I went into the site,  it would put me into an infinite loading screen, I am on chromebook if that helps but like I said this just started happening (I never used it on any other device) so yeah. The other issue was that sometimes, the messages wouldnt update and you would have to reload the site, this happens consistently when using gifs and sometimes when not.

**Comment by agnirudrasil** [comment]
Hello, thanks for creating this issue. The website is currently hosted on a very cheap VPS and it has run out of storage. Hence the Infinite loading.

I am not sure about the messages not updating, could you please elaborate

**Comment by agnirudrasil** [comment]
The website is now working as intended
